---
- name: Add config file for Debian
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian"

- name: Add config file for RedHat
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "RedHat"

- name: Stop mysql on RedHat
  service:
    name: mysqld
    state: stopped
  when: ansible_os_family == "RedHat"

- name: Stop mysql on Debian
  service:
    name: mysql
    state: stopped
  when: ansible_os_family == "Debian"

- name: Bootstrap the cluster
  shell: /usr/bin/mysqld_bootstrap
  run_once: true

- name: Start Mysql server for RedHat
  service:
    name: mysqld
    state: started
  when: ansible_os_family == "RedHat"

- name: Start MySQL service for Debian
  service:
    name: mysql
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Set root Password
  mysql_user:
    name: root
    host: localhost
    password: '{{ mysql_root_password }}'
    state: present
  run_once: true
