---
- name: Trigger handlers
  meta: flush_handlers

- name: Add config file for Debian
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian"
  notify: Start MySQL service for Debian

- name: Add config file for RedHat
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "RedHat"
  notify: Start Mysql server for RedHat

- name: Bootstrap the cluster and Set password
  block:
    - name: Bootstrap the cluster
      raw: /usr/bin/mysqld_bootstrap
      changed_when: true

    - name: Set Mysql password
      include_tasks: mysql_passwd.yml
  run_once: true

- name: Trigger handlers
  meta: flush_handlers
