---
###############
#Galera_cluster
###############
- name: Include variables for Debian
  include_vars: Debian.yml
  when: ansible_os_family == "Debian"

- name: Include variables for RedHat
  include_vars: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Installation of Galera Cluster on Ubuntu
  include_tasks: Debian.yml
  when: ansible_os_family == "Debian"

- name: Installation of Galera Cluster on CentOS
  include_tasks: Redhat.yml
  when: ansible_os_family == "RedHat"

- name: Configure Galera cluster
  include_tasks: conf.yml
  when: not master_slave_replication

# ######################################    
# # Configuration for Master-Slave setup
# ######################################
- name: Setup Master slave in galera cluster
  block:
    - name: Setup master
      include_tasks: master.yml
      when: (inventory_hostname in groups[ansible_hostfile_master_groupname])

    - name: Setup slave
      include_tasks: slave.yml
      when: (inventory_hostname in groups[ansible_hostfile_slave_groupname])
  when: master_slave_replication
